export const ADD_DRAFTED_PLAYER = 'ADD_DRAFTED_PLAYER"';

export const UPDATE_REMAINING_PICKS = ' UPDATE_REMAINING_PICKS';

export const SET_DRAFTING_TEAM = 'SET_DRAFTING_TEAM';

export const SET_TEAMS = 'SET_TEAMS';

export const SET_TEAM_CONFIGS = 'SET_TEAM_CONFIGS';

export const SET_DRAFT_READY = 'SET_DRAFT_READY';